name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Rust 2021
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run tests
        run: cargo test

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
